OSD: build fixes for Linux
Had to remove the #ifdef from SyslogModule.hpp because it wouldn't build on
Linux (undefined reference to vtable for SyslogModule) for some obscure reason.